DX: update Epic label to include emoji
ComPWA/policy pull request #469
Opened 2024-12-03 18:55 UTC by shenvitor

Closes #468

2024-12-03 19:00 UTC, shenvitor commented
To do this, I need additional changes for the PR linting / lint-pr / Check labels (pull_request) job

2024-12-03 20:48 UTC, redeboer commented
Well spotted 😁 That would be another PR in ComPWA/actions.

We also may have to add more repos to the `sync-labels.yml` workflow of this repo and run it through workflow dispatch once the PR has been merged. That's what the `labels.toml` is for.

2024-12-14 15:22 UTC, shenvitor commented
@redeboer I think for this PR the next step is for you (who have the right) to change the default labels, see if the check labels test  pass, and merge if it goes well :)

2024-12-17 12:35 UTC, redeboer approved these changes
Nice 🈺
We also need to update [this](https://github.com/ComPWA/actions/blob/3d758c6369d07e36abd8f93ea0aafe4e19c9e29a/.github/workflows/pr-linting.yml#L23) in order to close https://github.com/ComPWA/policy/issues/468.

2025-01-08 10:20 UTC, redeboer commented
@shenvitor could you address https://github.com/ComPWA/policy/pull/469#pullrequestreview-2508760343? Then probably we can merge this PR

2025-01-08 10:26 UTC, redeboer commented
See also this search:
https://github.com/search?q=org%3AComPWA+%2F%28%3F-i%29Epic%2F&type=code

But indeed, it's only ComPWA/actions and ComPWA/policy that needs to be updated.

2025-01-08 10:47 UTC, redeboer approved these changes
Thanks! 🔢

2025-01-08 10:50 UTC, redeboer requested changes

2025-01-08 10:50 UTC, redeboer commented on .github/workflows/sync-labels.yml
>            labels sync --filename labels/default.toml --owner ComPWA --repo update-pip-constraints
Are these all repos? You can list them with
```shell
gh repo list ComPWA --json name --jq '.[].name' | sort
```

2025-01-08 11:20 UTC, shenvitor commented on .github/workflows/sync-labels.yml
>            labels sync --filename labels/default.toml --owner ComPWA --repo update-pip-constraints
ok maybe easier to include all repos at first, see [c96e1b1](https://github.com/ComPWA/policy/pull/469/commits/c96e1b188d9d02c2478306c0c3582d3126c36d9b)

2025-01-08 11:50 UTC, merged